// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYER1_H_
#define FLATBUFFERS_GENERATED_PLAYER1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct Player1;
struct Player1Builder;

struct Player1 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Player1Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SCORE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t score() const {
    return GetField<int32_t>(VT_SCORE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_SCORE, 4) &&
           verifier.EndTable();
  }
};

struct Player1Builder {
  typedef Player1 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Player1::VT_NAME, name);
  }
  void add_score(int32_t score) {
    fbb_.AddElement<int32_t>(Player1::VT_SCORE, score, 0);
  }
  explicit Player1Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Player1> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Player1>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Player1> CreatePlayer1(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t score = 0) {
  Player1Builder builder_(_fbb);
  builder_.add_score(score);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Player1> CreatePlayer1Direct(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t score = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreatePlayer1(
      _fbb,
      name__,
      score);
}

inline const Player1 *GetPlayer1(const void *buf) {
  return ::flatbuffers::GetRoot<Player1>(buf);
}

inline const Player1 *GetSizePrefixedPlayer1(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Player1>(buf);
}

template <bool B = false>
inline bool VerifyPlayer1Buffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Player1>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedPlayer1Buffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Player1>(nullptr);
}

inline void FinishPlayer1Buffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Player1> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayer1Buffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Player1> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PLAYER1_H_
